/** Declaration file generated by dts-gen */

export class Tweenable {
    constructor(...args: any[]);

    dispose(): void;

    get(): any;

    isPlaying(): any;

    pause(): any;

    resume(): any;

    seek(e: any): any;

    set(t: any): void;

    setConfig(e: any): any;

    setScheduleFunction(e: any): void;

    stop(...args: any[]): any;

    tween(...args: any[]): any;

    static filters: {
        token: {
            afterTween: any;
            beforeTween: any;
            doesApply: any;
            tweenCreated: any;
        };
    };

    static now(): any;

    static setScheduleFunction(t: any): any;

}

export function interpolate(t: any, e: any, n: any, a: any, ...args: any[]): any;

export function setBezierFunction(t: any, e: any, n: any, r: any, u: any): any;

export function tween(...args: any[]): any;

export function unsetBezierFunction(t: any): any;

export namespace Tweenable {
    namespace formulas {
        function bounce(t: any): any;

        function bouncePast(t: any): any;

        function easeFrom(t: any): any;

        function easeFromTo(t: any): any;

        function easeInBack(t: any): any;

        function easeInCirc(t: any): any;

        function easeInCubic(t: any): any;

        function easeInExpo(t: any): any;

        function easeInOutBack(t: any): any;

        function easeInOutCirc(t: any): any;

        function easeInOutCubic(t: any): any;

        function easeInOutExpo(t: any): any;

        function easeInOutQuad(t: any): any;

        function easeInOutQuart(t: any): any;

        function easeInOutQuint(t: any): any;

        function easeInOutSine(t: any): any;

        function easeInQuad(t: any): any;

        function easeInQuart(t: any): any;

        function easeInQuint(t: any): any;

        function easeInSine(t: any): any;

        function easeOutBack(t: any): any;

        function easeOutBounce(t: any): any;

        function easeOutCirc(t: any): any;

        function easeOutCubic(t: any): any;

        function easeOutExpo(t: any): any;

        function easeOutQuad(t: any): any;

        function easeOutQuart(t: any): any;

        function easeOutQuint(t: any): any;

        function easeOutSine(t: any): any;

        function easeTo(t: any): any;

        function elastic(t: any): any;

        function linear(t: any): any;

        function swingFrom(t: any): any;

        function swingFromTo(t: any): any;

        function swingTo(t: any): any;

        namespace bounce {
            const prototype: {
            };

        }

        namespace bouncePast {
            const prototype: {
            };

        }

        namespace easeFrom {
            const prototype: {
            };

        }

        namespace easeFromTo {
            const prototype: {
            };

        }

        namespace easeInBack {
            const prototype: {
            };

        }

        namespace easeInCirc {
            const prototype: {
            };

        }

        namespace easeInCubic {
            const prototype: {
            };

        }

        namespace easeInExpo {
            const prototype: {
            };

        }

        namespace easeInOutBack {
            const prototype: {
            };

        }

        namespace easeInOutCirc {
            const prototype: {
            };

        }

        namespace easeInOutCubic {
            const prototype: {
            };

        }

        namespace easeInOutExpo {
            const prototype: {
            };

        }

        namespace easeInOutQuad {
            const prototype: {
            };

        }

        namespace easeInOutQuart {
            const prototype: {
            };

        }

        namespace easeInOutQuint {
            const prototype: {
            };

        }

        namespace easeInOutSine {
            const prototype: {
            };

        }

        namespace easeInQuad {
            const prototype: {
            };

        }

        namespace easeInQuart {
            const prototype: {
            };

        }

        namespace easeInQuint {
            const prototype: {
            };

        }

        namespace easeInSine {
            const prototype: {
            };

        }

        namespace easeOutBack {
            const prototype: {
            };

        }

        namespace easeOutBounce {
            const prototype: {
            };

        }

        namespace easeOutCirc {
            const prototype: {
            };

        }

        namespace easeOutCubic {
            const prototype: {
            };

        }

        namespace easeOutExpo {
            const prototype: {
            };

        }

        namespace easeOutQuad {
            const prototype: {
            };

        }

        namespace easeOutQuart {
            const prototype: {
            };

        }

        namespace easeOutQuint {
            const prototype: {
            };

        }

        namespace easeOutSine {
            const prototype: {
            };

        }

        namespace easeTo {
            const prototype: {
            };

        }

        namespace elastic {
            const prototype: {
            };

        }

        namespace linear {
            const prototype: {
            };

        }

        namespace swingFrom {
            const prototype: {
            };

        }

        namespace swingFromTo {
            const prototype: {
            };

        }

        namespace swingTo {
            const prototype: {
            };

        }

    }

    namespace prototype {
        function dispose(): void;

        function get(): any;

        function isPlaying(): any;

        function pause(): any;

        function resume(): any;

        function seek(e: any): any;

        function set(t: any): void;

        function setConfig(e: any): any;

        function setScheduleFunction(e: any): void;

        function stop(...args: any[]): any;

        function tween(...args: any[]): any;

        namespace dispose {
            const prototype: {
            };

        }

        namespace get {
            const prototype: {
            };

        }

        namespace isPlaying {
            const prototype: {
            };

        }

        namespace pause {
            const prototype: {
            };

        }

        namespace resume {
            const prototype: {
            };

        }

        namespace seek {
            const prototype: {
            };

        }

        namespace set {
            const prototype: {
            };

        }

        namespace setConfig {
            const prototype: {
            };

        }

        namespace setScheduleFunction {
            const prototype: {
            };

        }

        namespace stop {
            const prototype: {
            };

        }

        namespace tween {
            const prototype: {
            };

        }

    }

    namespace setScheduleFunction {
        const prototype: {
        };

    }

}

export namespace interpolate {
    const prototype: {
    };

}

export namespace setBezierFunction {
    const prototype: {
    };

}

export namespace tween {
    const prototype: {
    };

}

export namespace unsetBezierFunction {
    const prototype: {
    };

}

